### ISSUE TITLE
Why are TANNER locations not loading with load_tenant_settings?

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#130]
Consistently, TANNER locations are not loading when using the the full locations.tsv file and it has been necessary to re-run the load_locations task with a file containing just the TANNER locations. When re-running load_locations it works, so all of the supporting tasks seem to be working. 

Maybe there is a limit to how many locations can be loaded in a single task and the `locations_post` method needs to be split into posts of several batches?

**Comment by shelleydoljack** [comment]
This was fixed by fixing the rows before TANNER locations in the locations.tsv file. Running this task and piping output to `tee` made it fail silently, so you couldn't see that the SUL-SDR location had the wrong values in libraryCode and primaryServicePointCode columns and causing the rake task to fail.
