### ISSUE TITLE
Figure out how to migrate bound-withs

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#140]
Related to #141

Non-SAL3 example:
    Parent: ckey 9949516
    Child: ckey: 9949518

SAL3 example:
    Parent: ckey 9197050
    Child: ckey 9197054

Documentation - https://docs.google.com/document/d/15MGnQgq_AIFMuXQy6fQBg-ttjisSmeX2duGSXj8VZzI/edit#

Note to test: There are a number of "big sets" in EAL that the model needs to accommodate. e.g. 9336335

**Comment by jlkalchik** [comment]
SPEC bound with no item cat 1. Only identified by 590 note:
Parent: ckey 3275745
Child: ckey 4556217

Largest bound with record with 608 unshadowed and 1 shadowed child records:
Parent: ckey 488090

Many child items connected to different records:
SAL3: Ckey 3333260
Green: Ckey 13454733
SAL (with 1 parent item): Ckey 88174

FED-DOCS bound with of DIGI-SCAN item:
Parent: ckey 7647872
Child: ckey 8596111

Two different libraries bound with:
Parent: ckey 52716
Child: ckeys 52720 and 52721

Copy 1 and 2 bound with in same library:
Parent: ckey 6421336
Child: ckey 1416225

2 BW-PARENT items and 8 child records:
Parent: ckey 1415799

Microfilm reel uses single call number, but does not have 590 or item cat 1:
MFILM 015:4 retrieves 65,162 catalog records in Searchworks.

Parent record type does not match child record type (SAL3 transfer script does not look at type since it does not affect circulation):
Parent: ckey 9269699
Child: ckey 9269691

Serial bound with: 
Parent: ckey 14267194
Child: ckey 365430

**Comment by shelleydoljack** [comment]
Was there a decision on which bound-with model to do? It seems we have to do the holdings:item bound-with in order to get circulation correct, yes?

**Comment by ahafele** [comment]
Yes, holdings:items bound-with is required. The instance model would be a nice to have.

**Comment by ahafele** [comment]
[story time on bound withs notes here Oct. 19.](https://docs.google.com/document/d/1Ub4cdion62k3teJlvDejkpqBQ09j_54z4fxCgqkJItw/edit#)

**Comment by ahafele** [comment]
See [comment](https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/244#issuecomment-1353312505) on #[244](https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/244) for latest on cleanup work.
