### ISSUE TITLE
What fields should map to patronBarcode?

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#180]
TL;DR:
map proxchipid to patronBarcode and custom field proxchipid.

**Comment by shelleydoljack** [comment]
Need to check if SIP2 requires patron barcode. Do we map mobile ID or proximity chip ID to patron barcode? The checkout/in apps should be able to be configured to use custom fields (where we have mobile ID and prox chip ID) but that is not what Darsi and Laszlo experienced when testing out. Is this a bug or is there more configuration needed?
Open folio issue to update SIP2 to look at other user fields: https://issues.folio.org/browse/UXPROD-3612

**Comment by jgreben** [comment]
Create a ticket for implementation in folio-tasks when this is decided.

**Comment by shelleydoljack** [comment]
According to https://issues.folio.org/browse/SIP2-83 , when sending externalSystemId instead of patron barcode to SIP2, if configured to not require credentials, it should find user and allow checkout. We don't want to require credentials. The Omnicard readers for the self-check machines will read mobileID or proxchipID from the device and send to the SIP2 to look up the patron. **We can put proxChipId in user barcode field in order to support self-checkout with the plastic card** (omnicard reader gets proxChipId and can find user in FOLIO because proxChipId is put in user barcode field in FOLIO). This route means users will not be able to use their mobile ID at self-check machines until https://issues.folio.org/browse/UXPROD-3612 is addressed.

**Comment by shelleydoljack** [comment]
Map proxChipId to patronBarcode and it's current mapping to the customField proxChipId.
