### ISSUE TITLE
OCLC integration

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#184]
Daily bib record exports to OCLC; Lane is weekly

Time estimate: We hope Data Export app will do this, needs analysis, 4 weeks if we have to do it ourselves; use tool that Lehigh uses?

**Notes doc: https://docs.google.com/document/d/1sEEIdQomNSD-mDpnBxjn6lwWoDGtBeRl98kXAXmmN6w/edit#heading=h.kh3eubx6sn8a** 

Integrations spreadsheet https://docs.google.com/spreadsheets/d/1J4ZG_rjekZF5cLe7_DgCpX6kJy5j3mWSeZHX54geMy8/edit#gid=0&fvid=222628708

**Comment by shelleydoljack** [comment]
We need to know what data is where that should be sent to OCLC. Then we can maybe set something up to run automatically from airflow to trigger data export jobs to create files of MARC records to send to OCLC. I expect metadata folks who are creating data to know the most about what we should be querying for records that should be sent to OCLC.

If we want to use the worldcat api https://developer.api.oclc.org/wc-metadata-v2 it looks like you POST/PUT/DELETE marcxml. Does data export give us marcxml? i think it just gives us marc21 so we'd have to crosswalk to marcxml to use the API.

**Comment by ahafele** [comment]
Vitus is hoping we can set our holdings by identifying records - maybe instance status of cataloged and date this is set `statusUpdatedDate` and sending just the ID number rather than entire record. Lehigh does something [similar](https://github.com/lehigh-university-libraries/folio-oclc-holdings). Meeting forthcoming to discuss further.

**Comment by ahafele** [comment]
Moved to Data Exports Epic
