### ISSUE TITLE
Update Finance Settings for FY23

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#207]
The following have been updated:

budgets.tsv
funds.tsv
budgets_allocatons.tsv
ledgers.tsv
fiscal-years.tsv

**Comment by shelleydoljack** [comment]
Loaded to folio-dev without deleting first. I got a bunch of these errors during the allocate budgets task:
```
{"errors"=>
  [{"message"=>"Budget not found for pair fiscalYear-fundId",
    "code"=>"genericError",
    "parameters"=>[]}],
 "total_records"=>1}
```
I think these ^ are because funds were removed between fy22 and fy23,

There were also a bunch of these errors, I think during the load budgets task:
```
{"errors"=>
  [{"message"=>"must not be null",
    "type"=>"1",
    "code"=>"-1",
    "parameters"=>[{"key"=>"transactionType", "value"=>"null"}]},
   {"message"=>"must not be null",
    "type"=>"1",
    "code"=>"-1",
    "parameters"=>[{"key"=>"currency", "value"=>"null"}]},
   {"message"=>"must not be null",
    "type"=>"1",
    "code"=>"-1",
    "parameters"=>[{"key"=>"source", "value"=>"null"}]},
   {"message"=>"must not be null",
    "type"=>"1",
    "code"=>"-1",
    "parameters"=>[{"key"=>"amount", "value"=>"null"}]}]}
```
Might also be b/c funds changed between fiscal years.

There were 417 of these errors:
```
{"errors"=>
  [{"parameters"=>[],
    "errors"=>
     [{"message"=>"must not be null",
       "type"=>"1",
       "code"=>"-1",
       "parameters"=>[{"key"=>"budgetId", "value"=>"null"}]}]}],
 "total_records"=>1}
``` 
I think I saw this before when loading funds with expense classes. I think this occurred during the load_funds task. I don't see that the new expense classes were loaded. This is the error for the new expense classes:
```
{"errors"=>
  [{"message"=>"Field Code must be unique",
    "code"=>"uniqueFieldExpenseClassCodeError",
    "parameters"=>
     [{"key"=>"field", "value"=>"Code"},
      {"key"=>"entity", "value"=>"ExpenseClass"}]}],
 "total_records"=>1}
```

**Comment by shelleydoljack** [comment]
Ok, I tried delete_expense_classes and then load_expense_classes and the new ones loaded. But when I tried to load funds again, of course I get the error that it cannot create a fund because the ID already exists. So I will try again with deleting budgets and funds, then reloading funds and budgets.

**Comment by shelleydoljack** [comment]
Have to run delete_budgets and delete_funds twice or more times b/c for some reason, even though I get no errors for the delete_budgets task, I still get `"Cannot delete fund.id = 577a3a2d-4d81-4d03-be4c-ed106c15cf2c because id is still referenced from table budget.",` errors in the first round of doing delete_funds.

**Comment by shelleydoljack** [comment]
OH, I see why all these budgets and funds cannot be removed, I was thinking the FY22 budgets need to be deleted but they don't. I can load new funds and new budgets. I forgot, expense classes are associated with budgets, not funds, so the FY23 budgets should get the new expenses classes. I guess I learned that I was able to delete the old expense classes even though they were supposedly associated with the FY22 budgets.

**Comment by shelleydoljack** [comment]
The budgets.tsv is missing new data for Business and Law.

I still don't understand why expense classes won't load when doing POST to budgets but it does work if we do update_budgets (PUT). :shrug: I'll add this to the Rake file so load_finance_settings will do it.

**Comment by shelleydoljack** [comment]
Ok, so some questions for @ahafele and @scanedastanford about deleting and reloading finance settings or not deleting finance settings on folio-test. I'm thinking I could do this:
- delete expense classes
- load new expense classes
- load fiscal years (to get FY23)
- load budgets
- update budgets (to get the new expense classes b/c for some reason it doesn't work to associate during budget creation)
- allocate budgets
- delete orders
- load orders based on new reports run in Symphony for FY23

Do we need to delete funds? If we delete funds, then I need to delete budgets. In order to delete budgets, I need to change fiscalYearCode in budgets.tsv to SUL2022 or else the old budgets won't get deleted. Lastly, do we need to update the funds and budgets data for Law and Business?

**Comment by scanedastanford** [comment]
We have new funds for FY23 so I'm not sure if that requires deleting the old ones first or if that means you can just add the new ones. I also just remembered that some funds were moved to different subjects, so those will have a different fund group for FY23. Will those just be updated or do they need to be reloaded again? Lastly, I checked with Law, Lane and Business and they said their funds did not change in FY23.

**Comment by shelleydoljack** [comment]
@scanedastanford OK, so it sounds like I should delete funds (because some have different groups now) and budgets. For Law and Business, the budgets in the new tsv are still for FY22, should I update those to FY23?

**Comment by shelleydoljack** [comment]
Tasks to run to re-load finance data, funds, and expense classes:
1. delete orders
2. delete budgets (fy22)
3. delete funds (fy22)
4. delete expense classes
5. load new expense classes
6. load fiscal years (to get FY23)
7. load funds (fy23)
8. load budgets (fy23)
9. update budgets (to get the new expense classes b/c for some reason it doesn't work to associate during budget creation)
10. allocate budgets
11. load orders (fy23)

**Comment by scanedastanford** [comment]
Yes, for Law and Business, the budgets should be updated to FY23. Sorry I forgot to do that!

**Comment by shelleydoljack** [comment]
Checklist for rake tasks run against okapi-test:
- [x] delete orders: run from Symphony `{ date; STAGE=prod rake acquisitions:delete_all_orders[50]; date; } > ~/delete_orders_foliotest.log 2>&1`
- [ ] acquisitions:delete_budgets
- [ ] acquisitions:delete_funds
- [ ] acquisitions:delete_expense_classes
- [ ] download new tsv for acquisitions data
- [ ] acquisitions:load_expense_classes
- [ ] acquisitions:load_fiscal_years
- [ ] acquisitions:load_funds
- [ ] acquisitions:load_budgets
- [ ] acquisitions:update_budgets
- [ ] acquisitions:allocate_budgets
- [ ] load orders: run from Symphony `{ date; STAGE=prod rake load_orders; date; } > ~/load_orders_foliotest.log 2>&1`

**Comment by shelleydoljack** [comment]
Ugh, so ^ this order isn't going to work. I tried delete_budgets and get:
```
{"errors"=>
  [{"message"=>"Can't delete budget that referenced with expense class",
    "code"=>"budgetExpenseClassReferenceError",
    "parameters"=>[]}],
 "total_records"=>1}
```
So then I tried, delete_expense_classes, and get:
```
{"errors"=>
  [{"message"=>
     "Cannot delete expense_class.id = 8ec04c0a-8168-44d4-ab6e-b2ed02a413d3 because id is still referenced from table budget_expense_class.",
    "code"=>"genericError",
    "parameters"=>[]}],
 "total_records"=>1}
```
Will have to troubleshoot tomorrow.

**Comment by shelleydoljack** [comment]
Probably need to write a task to disassociate the expense classes from the budgets in order to be able to delete the budgets.

**Comment by shelleydoljack** [comment]
New plan:
- [x] delete orders
- [x] rake acquisitions:update_expense_classes
- [x] rake acquisitions:load_fiscal_years
- [x] rake acquisitions:load_ledgers
- [x] rake acquisitions:load_funds
- [x] rake acquisitions:update_funds
- [x] rake acquisitions:load_budgets
- [x] rake acquisitions:update_budgets
- [x] rake acquisitions:allocate_budgets
- [x] rake acquisitions:load_org_vendors_sul
- [x] rake acquisitions:load_org_vendors_business
- [x] rake acquisitions:load_org_vendors_law
- [x] load orders: run from Symphony { date; STAGE=prod rake load_orders; date; } > ~/load_orders_foliotest.log 2>&1

@scanedastanford this new plan will update the funds with the new groups listed in the funds spreadsheet. If you want close the FY22 funds, you could set them to inactive in folio, i think. or we just leave them active (fund status = active is hardcoded when we load funds but we could probably change that if we find we end up using this code for maintaining stuff in folio).

**Comment by shelleydoljack** [comment]
@ahafele and @scanedastanford the [budget allocations](https://docs.google.com/spreadsheets/d/1efd4LuamCNSgF6C8PLUw14LqixVAnjh5zQ7W6rkPv80/edit?usp=sharing) are missing for some SUL budgets on lines 404-418. Are there no budgets for these funds in FY2023? If so, then I think we should leave them out of the spreadsheet.

**Comment by scanedastanford** [comment]
Ugh sorry about that! I added them in
