### ISSUE TITLE
Look into SpinOmatic integration for label printing from FOLIO

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#225]
### Analysis [**Documentation**](https://docs.google.com/document/d/1S1o62fsSnP2MVJXFWEVUpUAXcUtRivDUg2vUM4IpiVk/edit#) 

SpineOmatic - https://github.com/ExLibrisGroup/SpineOMatic
Cornell written integration to transform FOLIO json to expected xml - https://github.com/cul-it/setae-api

**Comment by ahafele** [comment]
Discussed in 12/26 libsys team meeting. Seems like we should be able to get spineomatic running and utilize the cornell code. Josh will likely test using remote desktop. More to come in new year...

**Comment by peetucket** [comment]
Writing up some analysis of the tasks for this ticket in order to estimate/schedule the work.  Will then close this ticket after Jeremy reviews.  We will spawn new tickets in this epic when the actual work begins and use this ticket as a reference.

We need to:

1. Install the Cornell Middleware (Setae API: https://github.com/cul-it/setae-api) in on-prem kubernetes cluster.  Work with libsys/ops as needed.
2. Install (VMWare or VirtualBox) + Windows on laptop (or ask Ops team to provide a virtual Windows enviroment).
3. Connect a printer to this windows instance (may be easier with VMWare on laptop than a virtual Windows server).
4. Install Spine-O-Matic (https://github.com/ExLibrisGroup/SpineOMatic) on this windows instance (either laptop or virtual server).
5. Configure Setae to talk to our test Folio okapi API instance: https://github.com/cul-it/setae-api/blob/main/.env.example
6. Configure Spine-O-Matic to talk to the Satae instance: https://github.com/ExLibrisGroup/SpineOMatic/wiki/Quick-Start-Guide----Installation
7. Run Spine-O-Matic and try and print a label for some barcodes in the test Folio instance.  Troubleshoot as needed.
8. Work with Libsys and Acquisitions staff to see if this solutions works.

Rough estimate for steps 1 - 7: ~2 engineers for ~2 weeks.   Step 8 may generate additional work.  If solution works, there will be additional work in installing/setup/training of staff, and that is out of scope for our current estimate.
