### ISSUE TITLE
Dates incorrect

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#254]
Date ordered is one day behind. Example: 4/2/2015 in FOLIO and 4/3/2015 in Symphony.  POL receipt date is also one day behind. 
Tenant timezone issue?

**Comment by ahafele** [comment]
@scanedastanford I have a note that says - same is true for receipt date. Is that in the POL or is my note wrong?

**Comment by shelleydoljack** [comment]
Ugh, yes, this is most certainly due to how the data is passed in the JSON, for example, PO 919297F15 in Symphony and the JSON we created is `"approvalDate":"2014-11-18"` and in folio UI it is "11/17/2014, 4:00 PM" but when looking at the json, we get: `"approvalDate": "2014-11-18T00:00:00.000+00:00",`. Our folio-test is configured for PST. And I suspect that this wouldn't just impact order records, but anywhere we are porting over a date, like date cataloged and all the loans and bills. Do we need to convert our dates to UTC for storage in the database and then rely on folio configuration to display it in PST/PDT? yuck

**Comment by shelleydoljack** [comment]
or do we configure the postgresdb to be PST/PDT and then the data and folio ui reconcile correctly?

**Comment by jgreben** [comment]
Yes the UI is supposed to reconcile UTC to PST. As long as the time stamp is correct it ought to work correctly, but I suspect something is wrong with the fact that the time stamp in question is `T00:00:00.000+00:00`

**Comment by shelleydoljack** [comment]
I tested doing a PUT for PO 919297F15 on folio-dev, passing this data for the dates: `"approvalDate": "2014-11-18T00:00:00.000-08:00"` n.b. -08:00 for timezone and now it displays as 11/18/2014 in the UI.

**Comment by shelleydoljack** [comment]
I logged into the folio db to check the default timezone and it is America/Los_Angeles. According to https://kaiwern.com/posts/2021/07/20/what-you-need-to-know-about-postgresql-timezone/, 

> The main takeaway here are:
> PostgreSQL always store the value internally in UTC.
> PostgreSQL will convert the input with timezone offset to UTC.
> PostgreSQL will assume the input timezone is the same as the system’s timezone if no timezone offset is specified.

Since the db default timezone is PST, I would think that it should be assuming our date inputs as PST when we do not specify anything in a date-time string, such as "2014-11-18". But that doesn't seem to be the case, probably because the dates are stored in a JSON blob and not a column in a table with datatype date-time (I don't know enough psql foo to check this in the sul_mod_orders_storage db or table).

**Comment by shelleydoljack** [comment]
Should be fixed when we reload orders since the code's been updated.
