### ISSUE TITLE
Law Order Line notes not migrated

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#256]
Law reports that they are not seeing their order line notes in FOLIO. example 6102L00. 
Can't verify at the moment due to test being down - ath

**Comment by shelleydoljack** [comment]
Their orderline and order extended info fields loaded:
![Screen Shot 2023-01-06 at 3.49.36 PM.png](https://images.zenhubusercontent.com/62964511c137fa350131daff/fd3e1105-1092-4f8b-a8b7-ab7a7f6178f6)

**Comment by ahafele** [comment]
@shelleydoljack We revisited this with Law and they would like the Orderline NOTE migrated as well. @scanedastanford agrees that this would be ok for SUL also. 
Jake is also asking about ACCOUNT, are we already mapping this?

**Comment by scanedastanford** [comment]
We decided to map it also as a PO note. We originally tried to map it to the POL vendor account field but it was complicated.

**Comment by shelleydoljack** [comment]
We are already grabbing all the orderline xinfo fields ACCOUNT for SUL and LAW and putting it in a place to be mapped easily to the corresponding FOLIO PO line so I rather not change that code if I don't have to. I'm not sure what was the issue when I was trying to do this on folio-dev before we upgraded to Nolana, but I was able to delete an order from folio-test and reload it with the ACCOUNT info. See https://folio-test.stanford.edu/orders/view/6d6ecd53-b545-5a61-928e-6c8c9170410e . 

As for this ticket: mapping the orderline xinfo field NOTE. Where does LAW want it in FOLIO? Map to order or purchase orderline? The easiest would be if we get all the orderline xinfo fields NOTE and map to their corresponding FOLIO po line, but is there a po line note field? I don't see one in the json schema. If there is no place to put the orderline xinfo NOTE in a FOLIO po line, then I suggest we map only the orderline 1 xinfo field NOTE (not all the orderlines' xinfo field NOTE's) to FOLIO order.

And to be clear, SUL is only mapping the order xinfo field NOTE to FOLIO order. We are not mapping any orderline xinfo field NOTE to FOLIO order or po line. The code for selecting these fields is in `/s/SUL/Bin/folio_symphony_extract/acquisitions/orders/run_reports.ksh` starting at line 81.

**Comment by scanedastanford** [comment]
Could you please map the orderline xinfo field NOTE to the PO note field, like the other xinfo fields such as COMMENT? You can do the same for both Law and SUL so that you can use the same script.

**Comment by shelleydoljack** [comment]
For the orderline xinfo field COMMENT, we map only orderline 1 xinfo field COMMENT to FOLIO po note field I think because we would get a bunch of duplicate COMMENT fields if we did all orderlines' xinfo COMMENT fields. Is that correct? Should we map just orderline 1 xinfo field NOTE to FOLIO po note field as well? 

Here is what the script is doing for both SUL and Law:
order xinfo fields mapped to folio po note: INSTRUCT,NOTE,COMMENT,MULTIYEAR,STREAMING,BIGDEAL,DATA
orderline xinfo fields that will be mapped to folio polines: ACCOUNT,FUND,SELECTOR
orderline xinfo fields from orderline 1 that will be mapped to folio order: DESC,COMMENT,CONTACT,NOTIFY

I see now that I should take out MULTIYEAR,STREAMING,BIGDEAL,DATA from Law's selection.

**Comment by scanedastanford** [comment]
I'm meeting with Jake today at 3pm because he has some questions. I am ok with mapping NOTE from just orderline 1, but I don't know about Law. I'll find out after the meeting.

**Comment by shelleydoljack** [comment]
Hmm, in the recent run of the order selection, it looks like LAW still has data in MULTIYEAR and BIGDEAL. Since BIGDEAL maps to tags and is somewhat of a controlled vocabulary, I keep any LAW BIGDEAL notes from getting into FOLIO. But since MULTIYEAR maps to PO note, it gets in, see https://folio-test.stanford.edu/orders/view/4481ee76-057b-5116-989e-36e3314ad053. Does LAW want their BIGDEAL notes migrated to FOLIO po note? And I guess I shouldn't remove these from LAW's selection since they have data in them that they might want, regardless of it being in an incorrect xinfo field.

**Comment by scanedastanford** [comment]
Law is also ok with mapping the orderline NOTE from just orderline 1 to the FOLIO po note.
Law wants their BIGDEAL notes migrated to FOLIO po note, not as a tag like SUL.

Lastly, Jake told me that Law puts a date in the Symphony orderline Date Loaded to mark that it was paid by pcard. Is there a way for you to exclude this from Law's order selection?

**Comment by shelleydoljack** [comment]
> Lastly, Jake told me that Law puts a date in the Symphony orderline Date Loaded to mark that it was paid by pcard. Is there a way for you to exclude this from Law's order selection?

@scanedastanford is this for the one "rollover" report law_singleord_pcard or all the others as well (single order rcvd 0 and 1 and recurring orders lin1 and 2)?

**Comment by shelleydoljack** [comment]
I found where the orderline date loaded is. I can edit the selection for Law to select records where `seldist -p=0`
```
seldist
-p selects distributions with the date loaded/delivered before (<), on (=), or
     after (>) the specified date.
```
and that should exclude the ones with an actual date. Should we still have an order select for order type PCARD for Law? 

Also, @scanedastanford this will exclude the orderline from the selection but not necessarily the entire order. Is that correct?  For instance, this order ID from LAW 1831L21 has multiple orderlines, some with no date loaded and some with date loaded.

**Comment by scanedastanford** [comment]
Jake said to exclude orderlines with an actual Date Loaded for any order type. And to do this for all their rollover reports. (And no, for recurring orders it won't exclude the entire order because orderline 1 will never have a Date Loaded.)

**Comment by ahafele** [comment]
Suzette confirms this can be closed.
