### ISSUE TITLE
Law - Map Symphony Orderline field: FUND to FOLIO line_description

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#257]
See line 64 [here](https://docs.google.com/spreadsheets/d/13bh1Dd-v_tC0A5iepeTxWVBjj2JLz3lmvFglFDjOcD4/edit#gid=215993364).

**Comment by shelleydoljack** [comment]
There are not any FUND orderline extended info entries for Law. The FUND orderline fields are already mpaped to line_description, as shown with example from SUL:
![Screen Shot 2023-01-06 at 4.00.19 PM.png](https://images.zenhubusercontent.com/62964511c137fa350131daff/1652a857-9209-40d0-8776-ab7274167246)

They have a lot of NOTE fields with "FUND is blah blah blah". If that is what they want mapped, then it needs to be fixed in Symphony, I think.
![Screen Shot 2023-01-06 at 4.02.59 PM.png](https://images.zenhubusercontent.com/62964511c137fa350131daff/0768d6e9-daa0-406a-81b2-e2727b24f3dd)

**Comment by ahafele** [comment]
@scanedastanford  will discuss with Jake. Law does not have any fund ext. info notes for orders or order lines. They are just in a "Note" field in symphony. Will need to fix in symphony or have a different mapping.

**Comment by scanedastanford** [comment]
Discussed with Law. They are ok with the fund being in the FOLIO PO Note field. Removed FOLIO line_description from mapping.

**Comment by shelleydoljack** [comment]
@scanedastanford should we still map it to line_description for SUL?

**Comment by scanedastanford** [comment]
Yes, for SUL please still map it to line_description. Thanks!
