### ISSUE TITLE
Create Inventory = None issue

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#268]
For receiving history to show in Inventory - Holdings the Create Inventory POL option must include Holdings. Currently we are migrating everything as none. 

Response from Dennis Bridges

_the way they were migrated is likely the crux here, yes. In order to have the display on Holdings option, the POL must actually contain a reference to a specific Holdings record rather than just a Location record. When create inventory is set to anything that does not include Holdings FOLIO will not worry about managing this link. In this case it will not know where to display the piece information on holdings and thus, the option does not appear. You would need to change the create inventory setting to make this available._

We should maybe talk with Charles at ID. Lane's POLs were all loaded as none, but I see in the mapping spreadsheet that on 12/12 Sonam asked this to be changed. I've asked Alex if this topic of Inventory Receiving History can be put on the next Lane/Index Data meeting agenda. 

Per Darsi - Jeff from Duke loads them as “None” and then sends a call to the storage endpoint to swtich them to “instance/holdings/items” so the receiving will work

**Comment by ahafele** [comment]
@scanedastanford can you confirm that we want receiving history to show in Inventory for migrated orders? My assumption is yes, in particular for serials.

**Comment by shelleydoljack** [comment]
https://github.com/sul-dlss/folio-tasks/issues/124

**Comment by shelleydoljack** [comment]
Hmm, maybe it is not as simple as adding "createInventory". What Dennis wrote makes me think that we should set the holdingsId in the locations object when we migrate the orders:
```
"locations": {
            "description": "a list of the location records for this purchase order line",
            "id": "locations",
            "type": "array",
            "items": {
              "description": "The location details",
              "type": "object",
              "$schema": "http://json-schema.org/draft-04/schema#",
              "properties": {
                "locationId": {
                  "description": "UUID of the (inventory) location record",
                  "type": "string",
                  "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
                },
                "holdingId": {
                  "description": "Holding UUID associated with order line",
                  "type": "string",
                  "$schema": "http://json-schema.org/draft-04/schema#",
                  "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
                },
                "quantity": {
                  "description": "combined/total quanitity of physical and electronic items",
                  "type": "integer"
                },
                "quantityElectronic": {
                  "description": "quantity of electronic items",
                  "type": "integer"
                },
                "quantityPhysical": {
                  "description": "quantity of physical items",
                  "type": "integer"
                }
              },
```
Right now, we are only setting locationId based on the[ Symphony holding code > location mapping](https://docs.google.com/spreadsheets/d/19nXAJgwUjXekwEpf4iOIyA1eWcaaKIo6wSfQg8Guqo4/edit?usp=sharing).

**Comment by shelleydoljack** [comment]
I deleted and reloaded order 912354F06 on folio-dev with a holdingId instead of a locationId (cannot have both or else the API gives an error) and I was able to receive a piece using the Receiving app. I had to add a piece first (not sure why a piece wasn't created when I reloaded the order like the other orders have) before I could receive it. After receiving a piece, the purchase order line shows quantity physical = 2 instead of 1. Not sure if that's right either. The "receiving history" still doesn't show anything in the linked holdings record in the Inventory app but the linked po line displays under Acquisition there.

I tried a second time, deleting and reloading the order on folio-dev with the holdingsId instead of locationId in the poline info section. I checked what it looked like in Receiving app and it still shows no piece under the Expected section (like last time). Then I updated the purchase orderline to have `createInventory: "Instance, Holding, Item"` using the endpoint `/orders-storage/po-lines/{id}`. Note that the purchaseOrderId and poLineNumber fields need to be included in doing this PUT request. There was still no piece under the Expected section in the Receiving app, so I added a piece, checking the "Display on holding" box (not sure if that was correct) and then received it. The receiving history shows on the holding record now.
![Screen Shot 2023-01-06 at 2 33 57 PM](https://user-images.githubusercontent.com/6343464/211103896-b4ad9d4a-0448-4e0b-88f9-7adfb0f2b0b5.png)

![Screen Shot 2023-01-06 at 2 35 52 PM](https://user-images.githubusercontent.com/6343464/211104122-fa631e4b-0db1-416a-a876-6b368ab8a330.png)

**Comment by shelleydoljack** [comment]
With another order on folio-dev, 318859F09, I only updated the purchase order line with `createInventory: "Instance, Holding, Item"` using the endpoint `/orders-storage/po-lines/{id}` instead of testing changing locationId to holdingId in the locations object of the po line. After updating the po line, I looked at the two GREEN-STACKS holdings on the inventory record and none of them had anything under Acquisition or Receiving History. I then went to the Receiving app and received v.5. Then I looked at the Inventory app and a new holdings record was created with the linked po line under Acquisition but nothing was under Receiving history. No item was added even though the createInventory should have created one, I think. 
![Screen Shot 2023-01-06 at 3 08 55 PM](https://user-images.githubusercontent.com/6343464/211108430-631957f2-9244-440b-ba4a-03f71fa32a4a.png)
So I think this means we need to use the holdingId instead of locationId in the location object for the purchase orders.

**Comment by ahafele** [comment]
@shelleydoljack for the third test you did where you "only updated the purchase order line with createInventory: "Instance, Holding, Item" using the endpoint /orders-storage/po-lines/{id} instead of testing changing locationId to holdingId" do you recall if the option to "Display on holding" was available _and_ checked? Another question is whether the Receiving workflow was synced or not. I'm sure you don't remember but this might explain why an item was not created. 
Suzette will do some more testing today. I'll update this ticket after.

**Comment by shelleydoljack** [comment]
I checked the display on holding box when I added a piece, so it was available but unchecked. Looking at the data I PUT for poline 912354F06-1, the receiving workflow (checkinItems field) was not synced:
```
"id" : "dda66c5f-5448-473f-8dc8-3c12b8e966c5",
  "checkinItems" : false,
```

**Comment by ahafele** [comment]
@shelleydoljack Suzette did some more testing and agrees that you should move forward with updating the purchase order line with createInventory: "Instance, Holding, Item" and changing locationId to holdingId.

**Comment by shelleydoljack** [comment]
Is addressed in new rake task.
