### ISSUE TITLE
Items not being added to correct holdings - Nolana Dev

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#292]
a2798312 
a2229858
a2162266
a765842
a1433159
a660592

**Comment by ahafele** [comment]
@jermnelson I was able to retrieve a2798312 using the query Shelley suggested to get the uuid. The holdings and items look good. I poked around for others in that range but I'm not stumbling across any others with multiple holdings/items. 
One thing to note - the stat codes are not showing on the item as they should. https://github.com/sul-dlss/folio_migration/issues/39

**Comment by jermnelson** [comment]
@ahafele -  while looking into the missing stat codes for the items, part of the problem is that the following statcodes in the https://github.com/sul-dlss/folio_migration/blob/main/mapping_files/statcodes.tsv are not in FOLIO dev environment.:

```WESTSIL3
WESTSIL5
WESTSIL9
WESTGOL3
WESTGOL1
WESTGOL2
W1SAL3
WESTGOL6
PC-TOSS
WESTBRO1
WESTGOL5
WESTSIL6
W2SAL3
WESTBRO2
WESTSIL8
WESTGOL8
DIGI-SENT
```
Another issue that that the `statisticalCodeIds` property is missing from the `item_mapping` files;  added mapping to [PR 48](https://github.com/sul-dlss/folio_migration/pull/48)

**Comment by ahafele** [comment]
Notes - a2208443 - items on correct holdings including copy 2. MHLDs not matching, but I think they should be. We are replaced 852 location code with SUL migration error - problem for trouble shooting?
