### ISSUE TITLE
Figure out mapping for loan types

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#322]
Currently we have a simple mapping by item type to assign loan types.
folio_name	ITEM_TYPE
Non-circulating	NONCIRC
Non-circulating	NH-INHOUSE
Non-circulating	LIBUSEONLY
Can circulate	*

We have requests based on things other than the item type though.
All items lib SPEC-COLL should be Non-circulating
library EDUCATION item type NH7-DAY should be curricshortloan7
library EARTH-SCI item type LCKSTK-EXP should be lckstk-expensive

All items lib HV-ARCHIVE should be Non-circulating
All items lib HOOVER should be Non-circulating
(but Rhea said in slack folio-support channel 11/9/22 "as part of our clean-up work, all HV-ARCHIVE and HOOVER records will be flipped to Type LIBUSEONLY before migration.”)

**Comment by shelleydoljack** [comment]
In a helper file for airflow, we have a method that updates the value of what is in the ITEM_TYPE column of the tsv for specific libraries so that the material type mapping could include additional values (esp. LIBRARY, FORMAT). https://github.com/sul-dlss/libsys-airflow/blob/be7457caab83e6f34716f9957228b13134aff449/plugins/folio/helpers/tsv.py#L18-L43
This impacts how we create our loan type mapping since we are modifying the tsv file. For instance, if the item type in the tsv generated from our extract scripts is "LIBUSEONLY", then this method will update the value of ITEM_TYPE to a concatenation of "ITEM_TYPE FORMAT LIBRARY" if the value in the LIBRARY column is GREEN, HOOVER, or HV-ARCHIVE. 🎉 Another example, for the ITEM_TYPE = NH-INHOUSE, the record format is concatenated, e.g "NH-INHOUSE MARC". So our loan type mapping will have to have all permutations of "NH-INHOUSE + \<FORMAT\>". 

I will start to work out something in a spreadsheet in the loan types folder.

**Comment by shelleydoljack** [comment]
Started a mapping in the [loan type mapping worksheet](https://docs.google.com/spreadsheets/d/13Y9KeHnLPUPjdaeUCPyA9fg2aIx12xNyisFjARKmKs4/edit?usp=sharing)

Going to need to do some special handling in airflow for EDUCATION and SPEC-COLL, see https://github.com/sul-dlss/libsys-airflow/issues/238

**Comment by Laszlo-J** [comment]
To confirm, the Circ subgroup never made a sheet for loan types. We captured them in our meeting notes, and added directly to test. Looks like Lane and GSB added more to test for their circ rules since then (e.g. '12-hour short term'.)

So your spreadsheet is now the archive for loan types.

**Comment by shelleydoljack** [comment]
> To confirm, the Circ subgroup never made a sheet for loan types. We captured them in our meeting notes, and added directly to test. Looks like Lane and GSB added more to test for their circ rules since then (e.g. '12-hour short term'.)
> 
> So your spreadsheet is now the archive for loan types.

Nope, the loan types in my mapping worksheet are from https://drive.google.com/file/d/1PoaqWUPri2pVsEbk5Zhj-qfgUg24227P/view?usp=share_link + the stuff FOLIO gives us already.

**Comment by shelleydoljack** [comment]
We don't [need to modify ITEM_TYPE in our tsv](https://github.com/sul-dlss/libsys-airflow/issues/238) in order to have ITEM_TYPE, LIBRARY, and FORMAT map to material type or loan type. (yay!)

@Laszlo-J and @dlrueda I updated the spreadsheets for [loan type mapping](https://docs.google.com/spreadsheets/d/13Y9KeHnLPUPjdaeUCPyA9fg2aIx12xNyisFjARKmKs4/edit?usp=sharing) and [material type mapping](https://docs.google.com/spreadsheets/d/1Y7FPe7FfaczzExI2dnyRZs6rAlChvZBP0uYIlqBIlUI/edit?usp=sharing). All we need is to fix the rows highlighted in red. Should we just use the first of duplicate values for ITEM_TYPE? Or do we add LIBRARY and FORMAT values? `*` means wildcard, so any.
