### ISSUE TITLE
Determine Preference for Data Loading Error Notification

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/FOLIO-Project-Stanford#344]
As part of the upcoming WC for the Data Loading framework, determine how users should be notified if a Vendor MARC record Import workflow fails. There are number of different options (and they do not necessarily need to be mutually exclusive):

- Tech services user receives an email
- Send message to a Slack channel
- Other?

**Comment by ahafele** [comment]
Would this be if the entire import failed or if there are errors in the import? Is it possible to specify this in the vendor management app? e.g. user indicates for a particular vendor and particular file type how and who should be notified?

**Comment by jermnelson** [comment]
@ahafele - this could be specified in the vendor management app; this ticket is for defining the specific requirements need for communicating errors.

**Comment by jmartin-sul** [comment]
* need to figure out specific requirements of who gets notified and how
* even if notifying an individual, will probably do so via email list, so that message is going to a role instead of one person, in case people are out for extended periods or leave or whatever.
* need to figure out which events exactly we notify on
