### ISSUE TITLE
do not migrate marcit brief records

### ISSUE THREAD

**Issue by michelleif** [sul-dlss/FOLIO-Project-Stanford#366]
<strong>Submitted By: </strong>sdoljack@stanford.edu
<strong>Description: </strong>I think we should consider getting a new set of records from SFX for MarcIt brief to load to Folio instead of migrating what we have in Symphony. It appears we have A LOT of records with really bad encoding from MarcIt in Symphony. I think these are CJK records. See https://folio-test.stanford.edu/inventory?filters=mode.068b5344-e2a6-40df-9186-1829e13cd344%2Clanguage.chi%2Clanguage.kor%2Clanguage.eng&segment=instances&sort=title 
<strong>Instance HRID: </strong>``
<strong>Patron barcode: </strong>``
<strong>FOLIO App: </strong>
<strong>Urgency: </strong>
<strong>Browser: </strong>

**Comment by ahafele** [comment]
I agree. These have been plaguing me while trying to bib QA. I'm not sure we know how to avoid getting these. 
@jlkalchik - thoughts on this?

**Comment by jlkalchik** [comment]
@shelleydoljack and @scanedastanford did some work earlier this year to improve the record errors received from SFX. At the time I pulled a list for Kay of the bad records and there were around 1900 of them: https://docs.google.com/spreadsheets/d/1zXHwAhOBv6q48hvBq7EAwJJw8S6ys173/edit?usp=sharing&ouid=117546871848547485676&rtpof=true&sd=true If what I remember is true about the fix to the records coming through marcit then if we could get an updated list of records from them somehow these could be loaded with the new eLoader process.

**Comment by shelleydoljack** [comment]
Yea, we could fix in Symphony if there's a way to tell MarcIt to give us another set of records we already have. If we wanted to exclude MarcIt brief records, we'd have to somehow de-select ckeys to export based on text in the 590 field, which would be too much when extracting from Symphony but might be do-able in a DAG in our airflow process (even then, it might slow things down too much for migrating 9 million records). Fixing in Symphony might be best.

**Comment by scanedastanford** [comment]
We established a fix for new Marcit records going forward. To fix the bad Marcit records that have already loaded, I have to deactivate the SFX target and run Marcit to delete them from Symphony, then activate the SFX target and run Marcit again to load them (correctly this time). I have just started this process last week. I have to do one target at a time so that I don't overload Marcit, and Marcit is run once a week, so it will take a few weeks for all the records to get reloaded correctly. I'll keep you posted on the progress.

**Comment by dlrueda** [comment]
@scanedastanford I’m sure we could run bigger files, or run them more often during the week, the code looks for a new file every day.  I think if it’s possible to get this done sooner it would be great, so we can maybe do another full load of records into FOLIO with as many things fixed as possible.  We’d like to do that this month.

**Comment by scanedastanford** [comment]
Ok, I can try to run Marcit daily starting today and see how many records are fixed in a week or two.

**Comment by shelleydoljack** [comment]
We discovered an issue with the proposed process. Records loaded as deletes don't actually get deleted until Sunday. So for instance, the 11/3/22 marcit load has this:
```
mr4100000012016485  한국화학공학회 추계학술발표논문집
Disposition: vendor record deleted
001 match, delete record CKEY 14005483
```
and then the 11/4/22 marcit load has this:
```
mr4100000012016485  한국화학공학회 추계학술발표논문집
Disposition: vendor record overlaid
001 match, overlay record CKEY 14005483
```
but the record ckey 14005483 was deleted on Sunday, 11/6/22. So we can't run marcit daily if the plan is to load the deactivated target records as deletes. @scanedastanford if you know that only the records that show up in your file with LDR/05=d are from the deactivated target that will then get re-activated, you could remove those delete records from the marcit file and then when you re-activate the target, the records will show up again. That way you can run them daily and not do deletes but just overlays.

**Comment by scanedastanford** [comment]
I won't be able to know which ones are actual deletes and which ones are deletes that I'm reactivating because the marcit file doesn't contain target names. Should I go back to running it weekly? I can just run bigger files per week.

Also, to correct last week's records, it sounds like I need to deactivate and reactivate them again.

**Comment by shelleydoljack** [comment]
That's too bad. Yea, maybe try larger files. Every time you expect records to be deleted, you need to wait until they actually get deleted on Sunday. :( 

To correct last week's, maybe you can just reload the 11/3 and 11/4 files with the delete records removed, since all those would have been deleted on 11/6?

**Comment by scanedastanford** [comment]
I forgot to update this ticket. After winter break, I had corrected as many records that I could by reloading them and sent the rest to Jeanette to withdraw them from Symphony (about 400 records). Irina and I decided that since they were unsearchable anyways, it was better to delete them than to correct them manually. And we will do this as a clean-up periodically so that they will not migrate to FOLIO.
