### ISSUE TITLE
Some periodical instance data was migrated with inconsistent material types

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#397]
https://github.com/sul-dlss/LibSysTasks/issues/816

Per Laszlo - Some instances have individual volumes mapped to the wrong material type. See HRID `a8669655` Some volumes imported as book, some as periodical. This is a journal, so all volumes should be material type = periodical.

**Comment by ahafele** [comment]
@Laszlo-J this is a data issue. Some items in Symphony have item type STKS-MONO which maps to book. Some have the correct item type of STKS-PERI which maps to periodical.

**Comment by michelleif** [comment]
what's next here? up to Data Control to clean up in Symphony?

**Comment by ahafele** [comment]
I think this could be done post-launch - clean-up in FOLIO.

**Comment by ahafele** [comment]
I think this could be done post-launch - clean-up in FOLIO.

**Comment by ahafele** [comment]
@jlkalchik is this something that is on the clean-up list by any chance? Could it be done in symphony data control?

**Comment by jlkalchik** [comment]
This is not on any clean-up list that I know of. While Metadata staff will sometimes fix these errors if we come across them I do not know of any large scale remediation planned or has ever been done since the type is really for circulation rules.

It would be possible to batch update them if there was a way to identify them. However, we would someone who is dealing with the circ rules and material types to produce the specs and let us know what changes are desired and how we can identify the right group of records to make the change. If this involves all SUL libraries and the coordinates we would also need confirmation from them this is the correct procedure to do.

The issue with just looking for format SERIAL with type STKS-MONO in BCA, is that is not a guarantee that the record format is not incorrect or the type was intentionally designated for a different loan period. I know MCU intentionally creates the serial records for analyzed series with STKS-MONO type so receivers know the individual records get the correct type.
