### ISSUE TITLE
Create “we will not fork FOLIO” document

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#427]
Recently Metadata subgroup asked if we could create stat codes from leader 06.  Alissa investigated and turns out the only way we could do this would be to fork FOLIO’s code base (mod-data-import).  Libsys consensus is we will NOT fork FOLIO code.

(Metadata didn’t know that what they were asking for would require this)

Libsys folks would like to point to a “policy document” saying Stanford won’t fork FOLIO code. (People who want changes need to advocate in SIGs for changes.)

**Comment by michelleif** [comment]
I added a section to our "Release Adoption Plan" doc describing this "we will not fork FOLIO" policy. Take a look @ahafele @dlrueda : https://docs.google.com/document/d/1aw1arjC2WiX6um49HsRZ31Lg9XYcuXSmQ0TH7FvSGGg/edit#heading=h.hh8oxgdmg2sa

**Comment by michelleif** [comment]
@dlrueda does above doc suffice?

**Comment by edsu** [comment]
I really like that you are drawing attention to this maintenance issue explicitly!

I wonder if it is worth adding a clause to the policy about forks that are created for contributing changes back to the project? This is often handy if you don't have permission to push branches to the originating Git repository.

The whole idea of open source is that (in theory) we can help improve software over time. It would be unfortunate if this policy unintentionally discouraged that?

Maybe the policy could focus on the deployment of forks into production and not preclude the use of forks for development? Or maybe that's a given...

**Comment by michelleif** [comment]
Thanks @edsu! In theory yes, a benefit of moving to FOLIO should be that we can make our own improvements and contribute them back to the project. In reality it's unclear whether a single institution can do this on their own. Even though FOLIO is open source, it seems that development happens in organized teams and only certain developments are prioritized for the roadmap, and it's unclear how an institution can contribute to the codebase without being on one of these teams, nor is there a clear process for an institution to contribute some development resources to these teams and to the roadmap, nor a process for developing things not on the roadmap and sharing those developments.
I added this sentence to the doc "When Stanford will have resources to contribute to development of the FOLIO codebase, this customization policy isn’t meant to preclude forking the FOLIO codebase in order to develop features and fixes intended to be contributed back to the community version of FOLIO." How does that sound?

**Comment by edsu** [comment]
Thank you @michelleif that is perfect! Maybe instead of saying "will have" you can say "has"?

**Comment by michelleif** [comment]
I removed the entire "When" clause.
