### ISSUE TITLE
Run boundwith job to update 590s with $b again 

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#499]
Now that all Spec Coll rare book items have real 36105 barcodes, run script again to populate 590$b with barcode.  This should get a lot more $b’s created for SPEC-COLL items.

**Comment by shelleydoljack** [comment]
I ran the script, here are the results in the `/s/SUL/OneTime/BoundWiths/update_bwchild_590.log`:
```
13:36:27  Start update_bwchild_590.pl
13:37:44  Number of unique BW-CHILD records: 209797
13:52:34  Number of BW-CHILD 590 notes with parent ckey in subfield c: 9319
13:52:35  Number of BW-CHILD 590 notes missing parent ckey and barcode: 793
13:52:35  Number bw parent ckeys pulled from BW-CHILD 590 notes: 9319
13:52:35  Number of 590 notes with parent ckey in subfield c matches number of ckeys gotten from 590 notes:
13:52:35  9319 = 9319
13:52:35  Number of ckeys with a BW-PARENT item: 1232
13:52:37  Number of BW-PARENT ckeys missing: 11
13:52:37  Number of BW-PARENT items missing: 0
13:52:47  Number of 1:m BW-CHILD to BW-PARENT records: 462
13:52:51  Number of m:m BW-CHILD to BW-PARENT records: 5655
13:52:51  Writing editmarc files to /s/SUL/OneTime/BoundWiths/EditmarcFiles
13:53:31  Number of BW-CHILD with 590 notes linked (880 fields): 0
13:53:31  Number of editmarc files written: 78
13:53:31  Finished
```
@dlrueda I'm not sure 78 records to be updated sounds right. It should be more?

**Comment by dlrueda** [comment]
There are 1,254 BW-PARENT items that were given a 36105 barcode.  I do some work and check and see if the rest of them had a $b with the auto-formatted barcode.

**Comment by dlrueda** [comment]
There were 3,901 BW-CHILD items that were given a 36105 barcode.  I output the 590 for these and looked for the string “item id” (which is in the 590$b, and then looked did a grep -v 36105.  There are 1,215 that are not “36105” and 393 that are 36105.

Not sure if we should try and do something about this.  I do have a file that contains the old itemID and the new barcode, if we have the time, and want to, script something.

File is /s/SUL/Dataload/SmartBarcodes/230424_SpecColl/BW-PARENT.items.after

**Comment by dlrueda** [comment]
@shelleydoljack does this logic sound ok:

make edit file like so
```
@590
~auto-bc~s~$auto-bc~$36105barcode~g
~auto-bc~s~$auto-bc~$36105barcode~g
~auto-bc~s~$auto-bc~$36105barcode~g
~auto-bc~s~$auto-bc~$36105barcode~g
```

and have one line for each of the barcodes sets in the BW-PARENT file I have.  Then cat all the BW-CHILD ckeys to it? So, don’t worry about writing a ton of editmarc files, just make one big one?  Then I think it’s just a quick awk command to put the lines together and write them to this file (add `@590` as first line manually afterwards)

**Comment by shelleydoljack** [comment]
So I pulled out the old barcodes from the file `/s/SUL/Dataload/SmartBarcodes/230424_SpecColl/BW-PARENT.items.after` and did `for i in cat spec_coll_bwparent_old_items; do grep $i <some files from /s/SUL/OneTime/BoundWiths >> spec_coll_tag_590s_with_old_bcs; done`. The 590 fields from BW-CHILD records that have "bound" in the 590 only results in 119 matches with the old BW-PARENT barcodes. The 590 fields that don't have a "bound" or "reel" note matches 1,228 of the old BW-PARENT barcodes. Looking at the update_bwchild.pl script, the grep for "bound" or "reel" is not case insensitive. So I fixed that and am running it again.

**Comment by shelleydoljack** [comment]
after re-running the script with case insensitive grep, the log shows these numbers:
```
18:31:56  Start update_bwchild_590.pl
18:33:15  Number of unique BW-CHILD records: 209821
18:49:13  Number of BW-CHILD 590 notes with parent ckey in subfield c and no 36105 barcode in subfield b: 17106
18:49:14  Number of BW-CHILD 590 notes missing parent ckey and barcode: 1398
18:49:14  Number bw parent ckeys pulled from BW-CHILD 590 notes: 17106
18:49:14  Number of 590 notes with parent ckey in subfield c matches number of ckeys gotten from 590 notes:
18:49:14  17106 = 17106
18:49:14  Number of ckeys with a BW-PARENT item: 3694
18:49:19  Number of BW-PARENT ckeys missing: 14
18:49:19  Number of BW-PARENT items missing: 0
18:49:41  Number of 1:m BW-CHILD to BW-PARENT records: 823
18:49:46  Number of m:m BW-CHILD to BW-PARENT records: 6817
18:49:46  Writing editmarc files to /s/SUL/OneTime/BoundWiths/EditmarcFiles
18:51:12  Number of BW-CHILD with 590 notes linked (880 fields): 7
18:51:12  Number of editmarc files written: 6757
18:51:12  Finished
```

**Comment by dlrueda** [comment]
That’s a lot of editmarc files written!  Did you already run catalog merge on those?

**Comment by shelleydoljack** [comment]
No. The next step would be to run the `/s/SUL/OneTime/BoundWiths/edmarc_on_dir.pl` script if everything looks okay. I'm going to review the files more closely today.

**Comment by shelleydoljack** [comment]
I grabbed the new BW-PARENT barcodes from /s/SUL/Dataload/SmartBarcodes/230424_SpecColl/BW-PARENT.items.after and grepped those from the file that contains the new 590 fields to add to bw child records and 1,418 590 fields get these new barcodes. This spreadsheet [bwchild_590s_add_subfieldb.xlsx](https://github.com/sul-dlss/FOLIO-Project-Stanford/files/12017628/bwchild_590s_add_subfieldb.xlsx) is of the data that the editmarc files were generated from. As far as I can tell, it looks okay for us to run the edmarc_on_dir script. And this spreadsheet [spec_coll_bwchild_590s_to_get_new_bcs.xlsx](https://github.com/sul-dlss/FOLIO-Project-Stanford/files/12017669/spec_coll_bwchild_590s_to_get_new_bcs.xlsx) is of the bw child records that will get a new barcode that matches a barcode in the file `/s/SUL/Dataload/SmartBarcodes/230424_SpecColl/BW-PARENT.items.after`. I think the edmarc_on_dir.pl script should be run to update these 590 fields.

However, I think we are potentially missing some due to the smart barcode update. The update_bwchild.pl script filters out 590 fields that have a real barcode in subfield b (because we don't want to add another subfield b with a barcode) but includes non-36105 barcodes in what qualifies as a BW-PARENT barcode to add a subfield b to the 590. So in the June update, subfield b's with non-36105 barcodes were added to 590 fields. I don't think we want to edit the script to overwrite subfield b's already in the 590 field since many were added by Data Control. So we need to do some find/replace for the 590 fields that have the old non-real barcode.

Okay, so I grepped for the non-real barcodes in the bwchild_590s file that was generated last night and put them in a new file. Then I did `for i in cat spec_coll_bwparent_old_bcs; do grep $i bwchild_590s_w_non36105_subfieldb >> spec_coll_bwchild_590s_with_non36105_bcs; done` to get the 590s that have the old barcode in them. It is this file we should use to replace the old barcode with the new barcode from `/s/SUL/Dataload/SmartBarcodes/230424_SpecColl/BW-PARENT.items.after` So maybe get the ckeys and subfield b's from that file to create the one big editmarc file that we'd run against the ckeys.

**Comment by dlrueda** [comment]
That all sounds perfect.  I think after 5pm tonight we run the edmarc_on_dir.pl script.

I’ll spend a bit of time today creating a big editmarc file for you to review to catch the 590s that need an auto-barcode replaced with the new 36105 barcode.

**Comment by shelleydoljack** [comment]
Ok, I edited the last run in crontab for tonight. `#05 22 11 07 * /s/SUL/OneTime/BoundWiths/edmarc_on_dir.pl /s/SUL/OneTime/BoundWiths/EditmarcFiles 2>&1` . I'll leave it commented out if you want to run it after adutext finishes or change the time to run before adutext.

**Comment by dlrueda** [comment]
@shelleydoljack 
I have created an editmarc file to replace the non36105 barcode with the 36105 barcode for the Spec BW-PARENT ckeys.
Please review /s/SUL/OneTime/BoundWiths

Spec590.edit
update_Spec590s.ksh
spec_coll_bwchild_590s_with_non36105_bcs.ckeys

and report files from a test run
Spec590_editmarc.out
Spec590_editmarc.err

If all that looks ok to you, I can run it tonight also, after the edmarc_on_dir script finishes.

**Comment by shelleydoljack** [comment]
AFAICT seems fine. go for it!

**Comment by shelleydoljack** [comment]
There were 39 "Input line too long errors" and 5 some other error ("Error on editmarc command for 728193, returned 35072"). See edmarc_on_dir.log file. Maybe I'll gather this together to see if Data Control can update them.

**Comment by dlrueda** [comment]
I think we should close this ticket, all of our work is done.  Data Control can fix the errors manually but I don’t think we’ll do more for 39 errors.
