### ISSUE TITLE
Allow access for Aeon server

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#528]
Atlas's Developers are ready to test the Folio Import addon prior to delivery. We used the credentials provided in the python script, but are receiving a 403 error. Could you allow our HQ IP through your firewall so we can test? 
 
216.54.57.225
 
Thank you,
Katie

**Comment by shelleydoljack** [comment]
Have a PR for it: https://github.com/sul-dlss/folio-k8s/pull/133
Needs to be merged and applied to platform-complete and okapi. Do the want to use folio-stage or folio-test?

**Comment by shelleydoljack** [comment]
from atlas, they gave us different IP addresses....
Atlas's developers have delivered the Folio Import Addon. I've installed it on your Sandbox server (and turned off all other addons so we can isolate testing for just this one).
 
However, you will need to allow traffic from the Aeon server(s) in order to test. Below are the server IPs for both Sandbox and Production. I'd recommend allowing both so that you won't run into any issues when we move to production.
 
Sandbox: 20.230.202.69
Production: 52.175.234.32

**Comment by shelleydoljack** [comment]
emailed to get clarification about ip addresses...

**Comment by shelleydoljack** [comment]
Clarification:

> The 216.54.57.22 was for our Atlas' developer's testing from our internal servers. Testing is now complete and the addon has been delivered. Going forward, Hoover staff will need to be able to test it in Sandbox and ultimately use it in Production. You can remove 216.54.57.22 and replace it with the two for the Hoover server.

**Comment by shelleydoljack** [comment]
https://github.com/sul-dlss/folio-k8s/pull/165

**Comment by shelleydoljack** [comment]
Updated folio-dev and folio-test. Not sure if we want to get complicated about aeon sandbox -> okapi-test and aeon production -> okapi-prod

**Comment by shelleydoljack** [comment]
folio-stage updated. waiting to do prod during non-business hours.

**Comment by jgreben** [comment]
https://github.com/sul-dlss/folio-k8s/pull/165 is merged.

**Comment by shelleydoljack** [comment]
IP addresses for the developer, sandbox, and prod Aeon envs were added to their corresponding okapi ingresses for the different folio namespaces.
