### ISSUE TITLE
Student users are imported with wrong enrollment date

### ISSUE THREAD

**Issue by Laszlo-J** [sul-dlss/FOLIO-Project-Stanford#553]
Undergrads (maybe grads too?) are imported with an invalid enrollment date. If you edit their user record, User app errors due to the date.

Happened before go-live but still seems to be occurring.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbzdrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--02ce9147b862b05e0a07a2b1391cba6d760f3bb5/image.png)

**Comment by Laszlo-J** [comment]
Don't know if this is related, but students with a dual-affiliation of student and temp staff are imported as Patron group = staff. Should be student.

![image](https://github.com/sul-dlss/FOLIO-Project-Stanford/assets/60452238/7b316a24-60cc-4fd4-8953-5d9e8ee0d1b0)

**Comment by jgreben** [comment]
This looks like it is fixed now. Please reopen if you notice otherwise.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTBpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7674c77349c30f1d2f8be826b8cd7c17dc008b9c/Screenshot%202023-11-30%20at%2013.35.38.png)
