### ISSUE TITLE
Live test for data exports

### ISSUE THREAD

**Issue by jgreben** [sul-dlss/FOLIO-Project-Stanford#627]
- [x] POD - full dump
- [x] POD - incremental
- [ ] GOBI
- [ ] OCLC

**Comment by shelleydoljack** [comment]
Alissa wants to look at the files that would be transmitted for the full dump to make sure the processing looks right.

**Comment by shelleydoljack** [comment]
Josh mentioned using httpbin to fake requests sent to test POD. If we do this, then we should remove the authentication token from the pod connection info in airflow. Otherwise, we could upload the data to the test stream by simply adding `url_params={"stream": "Test"}` to [pod_transmission.py](https://github.com/sul-dlss/libsys-airflow/blob/622f8ad48c23197d73d607a5b58cbeba88655caf/libsys_airflow/dags/data_exports/pod_transmission.py#L50)

**Comment by ahafele** [comment]
In progress for pod and gobi - https://docs.google.com/document/d/1LrClfJo235NtEUR3K5aFQmH1t01sfr9smmtndt8DFy4/edit

**Comment by ahafele** [comment]
Still in progress. Closing ticket and making bug tickets as needed.
