### ISSUE TITLE
GOBI data QA

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#643]
~~Updates and Deletes not a requirement for GOBI. Looks like they get filtered out when text file is written so maybe it is related to below.~~ 
~~We don't need to generate MARC files - only want to transmit the text file~~
- Not yet running on schedule

**Comment by jgreben** [comment]
Gobi is running on a schedule but it only runs once a week. However, we set it up so that we could upload a json file to the [airflow variables list](https://sul-libsys-airflow-dev.stanford.edu/variable/list/) in order to be able to override the default schedules. Then I changed `schedule_gobi_days` to `1`.
