### ISSUE TITLE
Try allocating funds

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/FOLIO-Project-Stanford#658]
Suzette will provide Shelley with a spreadsheet of dummy data to try and allocate funds on -stage and see if existing code still works. 
Real numbers will be available on 8/12

**Comment by scanedastanford** [comment]
We received the actual FY25 allocations today so here it is. We are closing the following 9 funds by making them inactive before rollover so that they won't have a budget for FY25:
BRUSLITI
DATAFILE2
FILMPERF
GOVINFOI
MEDIAINST
MEDIARES
MEDIEVAL
MIGRATE-ERR
SERVOS
[FY25 LIB Allocation for LibSys.xlsx](https://github.com/user-attachments/files/16568238/FY25.LIB.Allocation.for.LibSys.xlsx)

**Comment by shelleydoljack** [comment]
@scanedastanford the spreadsheet needs to have data that looks like this:
```
fundCode	fiscalYearCode	acqUnit_name	amount	currency	source	transactionType	description
FUND_NAME-SUL	FYCODE	SUL	10000	USD	User	Allocation	Fiscal year rollover budget allocations.
```

**Comment by scanedastanford** [comment]
Here it is: 
[FY25.LIB.Allocation.for.LibSys.2.xlsx](https://github.com/user-attachments/files/16592023/FY25.LIB.Allocation.for.LibSys.2.xlsx)
I had to adjust one of the funds, so the total is updated.

**Comment by shelleydoljack** [comment]
@scanedastanford I created the allocations on folio-stage. There are two funds that don't have FY SUL2025 budgets so no allocations were created: HO-SUL and WOODBURN-SUL.
