### ISSUE TITLE
How do we handle location INTERNET in FOLIO?

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#72]
Are online holdings given item records in FOLIO?  Will we still want to give them location INTERNET, and assign them a library SUL/LAW/BUSINESS/LANE/HILA?

This question will be answered in the analysis of how to do e-holdings, perhaps.

**Comment by shelleydoljack** [comment]
There is an item status of "Intellectual item" which is for things that do not have a physical item. So it could be used as the status for e-resources if it is decided to have an item record for these things.

**Comment by ahafele** [comment]
Working on collecting information from other institutions now. Will discuss in next ERM meeting.

**Comment by ahafele** [comment]
Topic was discussed at E-resources Subgroup. MD Subgroup will provide feedback by next week. Both recorded here - https://docs.google.com/document/d/10gfxYSq7zD78_tkSzioL1XKtfQTIgLtI-6z8RiRHkjQ/edit#
Alissa and Irina will write up a tentative plan from there.

**Comment by ahafele** [comment]
Topic has gone to both subgroups and a goal plan has been decided. More analysis needed and Alissa will make tickets from there.

**Comment by ahafele** [comment]
**Proposal**: 

1. We will create holdings for all Electronic Resources and NO items. 
2. Each Campus will need either an Electronic Location(s) under their Library or in SUL's case a separate Library for Electronic (or a SUL library) with various Electronic Location(s), e.g. Internet, SDR... We would like these to be consistent but do not have a good use case for making coordinates have additional Electronic Libraries. Two areas where data consistency could be useful are Reporting and SW. I recommend we move forward with a SUL Electronic Library and load those first as examples. See [#120](https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/120)
3. 856s will move from the MARC record into the FOLIO holdings record(s). SW algorithm could be used to help identify the appropriate full text 856s. See [#119](https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/119) . We will _not_ try to create a holdings for each publisher at this time. All 856s on a record will move to 1 holdings record. All 856 subfields need to map to FOLIO Holdings.

**Comment by ahafele** [comment]
We began some technical conversations at the [6/10 Libsys Meeting](https://docs.google.com/document/d/1Ub4cdion62k3teJlvDejkpqBQ09j_54z4fxCgqkJItw/edit#). 

Summary of above - We need to migrate (and then maintain) electronic holding. Could generate a .mrc file from Symphony, and have airflow find the “right” 856s from it and add a SUL-electronic holdings record to that instance with all the 856s/no item. If 856s from more than 1 source, a vendor update .mrc would replace holdings and lose other 856s. Could load each 856 to own holding, but determining how to do that is challenging because of mix of data in 856s. 

**Examples**

- SDR - 14184535 - 856 40 |u[https://purl.stanford.edu/gb066fk7861|xSDR-PURL|xitem|xrights:world](https://purl.stanford.edu/gb066fk7861%7CxSDR-PURL%7Cxitem%7Cxrights:world)
- SDR - 14057505 - 856 40 |u[https://purl.fdlp.gov/GPO/gpo171358|70](https://purl.fdlp.gov/GPO/gpo171358%7C70)
- E-resource - 14240796 - 856 40 |uhttp://doi.org/10.21627/2022sp
- E-resource from Eloader - 14125363 - 856 40 |uhttps://doi.org/10.3998/mpub.17577|70|yUniversity of Michigan Press |xProvider: University of Michigan Press |xCollection: Open Access|xeLoaderURL|xum4|xum1757
- Eloader on Print - 14230211 - 856 41 |zAvailable to Stanford-affiliated users.|uhttps://doi.org/10.1017/9781108874465|xWMS|yCambridge University Press|xProvider: Cambridge University Press|xpurchased|xeLoaderURL|xcz4|xczon1315754176
- Eloader with multiple vendors on print - 958727 - 
  - 856 41 |zAvailable to Stanford-affiliated users.|uhttps://stanford.idm.oclc.org/login?url=http://app.knovel.com/web/toc.v/cid:kpMH000007|yKnovel|xProvider: Knovel|xsubscribed|xeLoaderURL|xkn4|xknocm45844111
  - 856 41 |zAvailable to Stanford-affiliated users.|uhttps://stanford.idm.oclc.org/login?url=http://app.knovel.com/hotlink/toc/id:kpMH000007/marine-hydrodynamics|yKnovel|xProvider: Knovel|xsubscribed|xeLoaderURL|xkn4|xknocm45844111
  - 856 41 |zAvailable to Stanford-affiliated users.|uhttps://doi.org/10.7551/mitpress/4443.001.0001|yMIT Press Direct|xProvider: MIT Press Direct|xCollection: gratis|xpurchased|xeLoaderURL|xmk4|xmk4443
  - 856 41 |zAvailable to Stanford-affiliated users.|uhttp://ieeexplore.ieee.org/servlet/opac?bknumber=6267419|xWMS|yIEEE Xplore Digital Library|xProvider: IEEE|xCollection: MIT Press eBooks|xpurchased|xeLoaderURL|xmp4|xmpocm45844111
  - 856 41 |zAvailable to Stanford-affiliated users.|uhttp://ieeexplore.ieee.org/servlet/opac?bknumber=6267419|xWMS|yIEEE Xplore Digital Library|xProvider: IEEE|xCollection: IEEE-Wiley eBooks|xpurchased|xeLoaderURL|xxp4|xxpocm45844111
- Eloader with multi-volume - 1451677 - 
  - 856 41 |3Vol.1|zAvailable to Stanford-affiliated users.|uhttps://stanford.idm.oclc.org/login?url=https://www.sciencedirect.com/science/book/9780124528017|yScienceDirect|xProvider: Elsevier|xpurchased|xeLoaderURL|xes4|xesocn572604204
  - 856 41 |3Vol.2|zAvailable to Stanford-affiliated users.|uhttps://stanford.idm.oclc.org/login?url=https://www.sciencedirect.com/science/book/9780124528024|yScienceDirect|xProvider: Elsevier|xpurchased|xeLoaderURL|xes4|xesocn572604204 …
- Hoover Archive Finding Aid - 13170428 - 856 42 |3Finding aid|uhttps://oac.cdlib.org/findaid/ark:/13030/c8r78mzs/
- Spec Finding Aid - 4332640 - 856 42 |3Finding aid available online|uhttp://www.oac.cdlib.org/findaid/ark:/13030/tf109n9832

**Comment by dlrueda** [comment]
Marc file of the above ckeys made, named SAMPLE856s.ckeys.0000.mrc

**Comment by ahafele** [comment]
@jermnelson @dlrueda we have a proposed path forward for this work. Because of the issues with moving the 856s to holdings or items, we will leave the 856s on the MARC SRS record and let them move to the instance record through the default marc to instance mapping. 
We would like to still create a holdings record based on the existence of one or more full-text 856 (same logic as before). So for [this example](https://folio-test.stanford.edu/inventory/view/4df1a09f-844b-5319-b31b-04e53d7e31b4) the holdings record would be the same, BUT the holdings notes (derived from 856 data) and the Electronic Access information (urls etc.) would be removed.   

This is a simplification of the initial idea so that we can move forward with migration. If possible, I think worthwhile to save the work done initially to potentially be used or referenced in the future.

**Comment by ahafele** [comment]
@jermnelson @dlrueda here is what still needs to be done regarding Electronic Resources. 

1. Remove 856 data from Holdings Electronic Access - will show at instance level through default mapping.
-- >Still seeing here - https://folio-dev.stanford.edu/inventory/view/938f90e2-b035-5b40-81de-4d400812fee4/9802f9cf-5b31-5d9f-8973-cfba4a749b12?filters=holdingsPermanentLocation.e1272fa4-e625-4e82-bda1-be6e9946a611&segment=holdings&sort=title   
3. Create 1 holdings record based on ~~: Existence of a Symphony Location = INTERNET item
Or~~ a “full text” 856 based on the SW definition. Spec should be based on https://consul.stanford.edu/display/NGDE/AccessAndUrlAlgorithms and https://github.com/sul-dlss/SearchWorks and /blob/3ede5f354d7b29f24af30e0bfc13b5aa122beefe/app/models/concerns/index_links.rb#L57-L59
-->This url is not full-text https://folio-dev.stanford.edu/inventory/view/938f90e2-b035-5b40-81de-4d400812  
4. For 2 check 596 for the owning Library and set Holdings Permanent location based on that. See spec here - https://github.com/sul-dlss/libsys-airflow/issues/129  
Exception: SDR urls should be Holdings Permanent location of SUL SDR. What is the spec used here? --> Looks for https://purl.stanford

**Comment by ahafele** [comment]
Currently we are only handling part 2 of the 3 part [SW algorithm](https://consul.stanford.edu/display/NGDE/AccessAndUrlAlgorithms) to determine "full text" urls. We still need to handle 956s with sfx data and finding aid urls. I will create new tickets for those and am closing this ticket.
