### ISSUE TITLE
Figure out which “on order” bibs need to be loaded to FOLIO so orders can be migrated

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss/FOLIO-Project-Stanford#99]
We need to figure out how many Symphony bibs with a call number structure but no item and a linked open order (open order = in this fiscal year)

While doing this it would be good to find bibs with call number structure with no items and no linked open order.  Basically bibs we really wouldn’t want to migrate, or we should review carefully

**Comment by shelleydoljack** [comment]
Spreadsheet of data: [Ckeys with zero copies](https://docs.google.com/spreadsheets/d/1V6AZBlt1917N6idw5i8CPjr49NZ6g_RFkKUONSKxrkA/edit?usp=sharing) - and either a linked order or no linked order.

**Comment by shelleydoljack** [comment]
@vitustang will ask cat coordinators about the "zero copy bibs no orders" tab.

**Comment by shelleydoljack** [comment]
For the tab "zero copy bibs with orders", discussion will be done in the Acq subgroup.

**Comment by shelleydoljack** [comment]
Spreadsheet updated to make sure only records with 1 call segment and 0 copies is selected.

**Comment by shelleydoljack** [comment]
Workfiles and howto in `/s/SUL/OneTime/OnOrderBibs`

**Comment by shelleydoljack** [comment]
Awaiting decisions from metadata and acq groups about records in spreadsheet.

**Comment by vitustang** [comment]
The ones in the "no item, no order" spreadsheet will be discussed in the Symphony Catcoord meeting on 4/12/22. I will report back afterward

**Comment by vitustang** [comment]
I have distributed [this spreadsheet](https://docs.google.com/spreadsheets/d/1Her0rlxzVhF4oQ9EXeNg3EN6_e7OoyVf/edit?usp=sharing&ouid=106628080535901581995&rtpof=true&sd=true) to the Symphony Catcoord and asked them to review the "no item, no order" records in their libraries. That's going to take some time. Since these don't have orders, my suggestion is that you ignore them for the time being. Some will get deleted as people review them

**Comment by ahafele** [comment]
@dlrueda I think this ticket can be closed or moved to a new actionable ticket. See Vitus' comments above.
